//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 

namespace B2MML.NET
{ 
/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mesa.org/xml/B2MML-V0600")]
[System.Xml.Serialization.XmlRootAttribute("ConfirmBOD", Namespace="http://www.mesa.org/xml/B2MML-V0600", IsNullable=false)]
public partial class ConfirmBODType {
    
    private TransApplicationAreaType applicationAreaField;
    
    private ConfirmBODTypeDataArea dataAreaField;
    
    /// <remarks/>
    public TransApplicationAreaType ApplicationArea {
        get {
            return this.applicationAreaField;
        }
        set {
            this.applicationAreaField = value;
        }
    }
    
    /// <remarks/>
    public ConfirmBODTypeDataArea DataArea {
        get {
            return this.dataAreaField;
        }
        set {
            this.dataAreaField = value;
        }
    }
}
}
